zuul:
  strip-prefix: false

ribbon:
  eureka:
    enabled: false
uw:
  cert-authentication:
    certificateNameHeader: X_CERTIFICATE
  profile:
    security:
      authentication-header-name: auth-header

spring:
  cache:
    cache-names: acs-users, authorized-uri, authorized-profiles-uri, user-groups, direct-user-groups
    caffeine:
      spec: maximumSize=1, expireAfterAccess=1m