zuul:
  strip-prefix: false
  include-debug-header: true
  routes:
    default:
      path: /**
      url: http://localhost:12345/
  CertificateAuthenticationFilter:
    pre:
      disable: False

gws:
  keystoreLocation: /keystore/location
  keystorePassword: password

spring:
  pid:
    fail-on-write-error: false
  cache:
    type: none

uw:
  cert-authentication:
    certificateNameHeader: X_CERTIFICATE_SUBJECT_NAME
  aws:
    dynamoDBEndpointOverride: http://localhost:8123
    dynamoDBCreateTable: true
    region: us-west-2
    acsUserSyncFunctionName: acs-user-sync-function-name
  profile:
    security:
      authentication-header-name: x-uw-act-as

ribbon:
  eureka:
    enabled: false