name: "edm-zuul-proxy: CI Build"

on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and test artifacts
        run: ./gradlew build
        env:
          USER: ${{ secrets.EDM_GITHUB_USER }}
          GITHUB_PAT: ${{ secrets.EDM_GITHUB_PAT }}
      - name: Publish package to github packages
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Notification
        if: ${{ failure() }}
        uses: uw-it-edm/notify-microsoft-teams@master
        with:
          webhook_url: ${{ secrets.MSTEAMS_CI_BUILDS }}
          job: ${{ toJson(job) }}
